name: Publish to G-Drive
on: 
  push: 
    branches: [ "main" ]
  pull_request: 
      branches: [ "main" ]

jobs:
  my_job:
    runs-on: ubuntu-latest

    steps:

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Upload to gdrive
        uses: adityak74/google-drive-upload-git-action@main
        with:
          credentials: ${{ secrets.credentials }}
          filename: "../out/artifacts/jabberpoint_jar/jabberpoint.jar"
          folderId: ${{ secrets.folderId }}
          overwrite: "true"
          